<?php

namespace CoreBundle\Repository;

/**
 * CompanyProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompanyProductRepository extends \Doctrine\ORM\EntityRepository
{
}
